rsync -rlptzv \
    --delete \
    --progress \
    --exclude=.svn \
    --exclude=.enb \
    --exclude=.git \
    --exclude=.idea \
    --exclude=.veendor \
    --exclude=.vscode \
    --exclude=build \
    --exclude=client.next \
    --exclude=coverage \
    --exclude=desktop.bundles \
    --exclude=flow-typed \
    --exclude=freeze \
    --exclude=html_reports \
    --exclude=app \
    --exclude=marketnode \
    --exclude=/reports \
    --exclude=configs/webpack/legacy.manifest.json \
    --exclude=node_modules \
    --exclude=server.sock \
    --exclude=luster-ctrl.sock \
    --exclude=version /Users/moonw1nd/Documents/develop/work/arcadia/market/front/apps/affiliate/ $REMOTE_DEV_SERVER://home/moonw1nd/affiliate_moonw1nd/
