require("moonw1nd.lsp.tsserver")
require("moonw1nd.lsp.sumneko_lua")
require("moonw1nd.lsp.efm")
require("moonw1nd.lsp.cssls")
require("moonw1nd.lsp.bashls")
require("moonw1nd.lsp.eslint")
require("moonw1nd.lsp.pyright")
require("moonw1nd.lsp.html")
